@startuml
interface xyz.innky.graduationproject.web.service.TeacherService {
~ Page<TeacherVo> getAllTeacher(Integer,Integer,String,Integer,String,Integer)
~ List<Teacher> searchAllByDepartmentId(Integer)
~ Integer searchAllCountByDepartmentId(Integer)
~ List<Teacher> getAllTeachersByName(String)
}
interface xyz.innky.graduationproject.web.service.SCourseTimeRelationService {
}
interface xyz.innky.graduationproject.web.service.MaterialService {
}
interface xyz.innky.graduationproject.web.service.SpecificCourseService {
}
interface xyz.innky.graduationproject.web.service.ExerciseSceneRelationService {
}
class xyz.innky.graduationproject.web.service.impl.UserAccountServiceImpl {
~ StudentService studentService
~ TeacherService teacherService
~ RoleMenuRelationService roleMenuRelationService
~ MenuService menuService
+ UserDetails loadUserByUsername(String)
+ Page<UserAccount> getAdminAccounts(Integer,Integer,String)
+ Page<UserAccountStuVo> getStudentAccounts(Integer,Integer,String,Integer,String)
+ Page<UserAccountTeacherVo> getTeacherAccounts(Integer,Integer,String,Integer,String)
+ List<MenuVo> getMenu()
}
interface xyz.innky.graduationproject.web.service.DeviceService {
~ Page<DeviceVo> getAllDeviceByConditionAndPage(String,String,String,String,String,Integer)
}
interface xyz.innky.graduationproject.web.service.StudentExerciseRelationService {
}
interface xyz.innky.graduationproject.web.service.MenuService {
~ List<MenuVo> getMenusByMenuIds(List<Integer>)
}
class xyz.innky.graduationproject.web.service.impl.DeviceServiceImpl {
~ ImageService imageService
+ Page<DeviceVo> getAllDeviceByConditionAndPage(String,String,String,String,String,Integer)
}
class xyz.innky.graduationproject.web.service.impl.SceneServiceImpl {
+ Page<Scene> getAllByConditionAndPage(Integer,Integer,Integer,String)
}
class xyz.innky.graduationproject.web.service.impl.ImageServiceImpl {
+ Page<Image> getAllImagesOnConditionAndPage(Integer,Integer,String,String,Integer)
+ boolean removeById(Serializable)
}
interface xyz.innky.graduationproject.web.service.DutyService {
~ List<Duty> searchAllByStudentId(Integer)
}
class xyz.innky.graduationproject.web.service.impl.DepartmentServiceImpl {
~ TeacherService teacherService
+ Page<DepartmentVo> getAllDepartment(Integer,Integer,Integer,String)
}
interface xyz.innky.graduationproject.web.service.DeviceSceneRelationService {
}
interface xyz.innky.graduationproject.web.service.UserAccountService {
~ Page<UserAccount> getAdminAccounts(Integer,Integer,String)
~ Page<UserAccountStuVo> getStudentAccounts(Integer,Integer,String,Integer,String)
~ Page<UserAccountTeacherVo> getTeacherAccounts(Integer,Integer,String,Integer,String)
~ List<MenuVo> getMenu()
}
class xyz.innky.graduationproject.web.service.impl.ExerciseServiceImpl {
}
interface xyz.innky.graduationproject.web.service.TeacherCourseClassRelationService {
}
class xyz.innky.graduationproject.web.service.impl.RoleServiceImpl {
}
interface xyz.innky.graduationproject.web.service.StudentService {
~ Page<StudentVo> getAllStudents(Integer,Integer,String,Integer,String,String,String,String,String)
~ Long selectCountByClassId(Integer)
~ List<Student> getStudentsByClass(Integer)
~ List<Student> getAllStudentsByName(String)
}
interface xyz.innky.graduationproject.web.service.StudentDeviceRelationService {
}
interface xyz.innky.graduationproject.web.service.DepartmentService {
~ Page<DepartmentVo> getAllDepartment(Integer,Integer,Integer,String)
}
interface xyz.innky.graduationproject.web.service.ClassInfoService {
~ Page<ClassInfoVo> getAllClass(Integer,Integer,String,String,String,String)
~ ClassInfo selectByClassId(Integer)
~ Page<ClassInfoVo> getAllClassWithoutTotal(int,int,String,String,String,String)
~ List<Student> getStudentsByClass(Integer)
}
interface xyz.innky.graduationproject.web.service.CourseService {
~ List<Course> getAllCoursesByStuid(Integer)
}
interface xyz.innky.graduationproject.web.service.CourseTimeService {
}
class xyz.innky.graduationproject.web.service.impl.TeacherServiceImpl {
+ Page<TeacherVo> getAllTeacher(Integer,Integer,String,Integer,String,Integer)
+ List<Teacher> searchAllByDepartmentId(Integer)
+ Integer searchAllCountByDepartmentId(Integer)
+ List<Teacher> getAllTeachersByName(String)
}
class xyz.innky.graduationproject.web.service.impl.RoleMenuRelationServiceImpl {
+ List<RoleMenuRelation> getListByRoleId(Integer)
}
class xyz.innky.graduationproject.web.service.impl.StudentExerciseRelationServiceImpl {
}
class xyz.innky.graduationproject.web.service.impl.ClassInfoServiceImpl {
~ StudentService studentService
+ Page<ClassInfoVo> getAllClass(Integer,Integer,String,String,String,String)
+ ClassInfo selectByClassId(Integer)
+ Page<ClassInfoVo> getAllClassWithoutTotal(int,int,String,String,String,String)
+ List<Student> getStudentsByClass(Integer)
}
interface xyz.innky.graduationproject.web.service.SceneService {
~ Page<Scene> getAllByConditionAndPage(Integer,Integer,Integer,String)
}
interface xyz.innky.graduationproject.web.service.ImageService {
~ Page<Image> getAllImagesOnConditionAndPage(Integer,Integer,String,String,Integer)
~ boolean removeById(Serializable)
}
class xyz.innky.graduationproject.web.service.impl.CourseTimeServiceImpl {
}
interface xyz.innky.graduationproject.web.service.RoleService {
}
interface xyz.innky.graduationproject.web.service.ExerciseService {
}
class xyz.innky.graduationproject.web.service.impl.MaterialServiceImpl {
}
class xyz.innky.graduationproject.web.service.impl.TeacherCourseClassRelationServiceImpl {
}
class xyz.innky.graduationproject.web.service.impl.StudentDeviceRelationServiceImpl {
}
class xyz.innky.graduationproject.web.service.impl.DeviceSceneRelationServiceImpl {
}
interface xyz.innky.graduationproject.web.service.RoleMenuRelationService {
~ List<RoleMenuRelation> getListByRoleId(Integer)
}
class xyz.innky.graduationproject.web.service.impl.CourseServiceImpl {
~ TeacherCourseClassRelationMapper teacherCourseClassRelationMapper
~ StudentMapper studentMapper
~ CourseMapper courseMapper
+ List<Course> getAllCoursesByStuid(Integer)
}
class xyz.innky.graduationproject.web.service.impl.DutyServiceImpl {
+ List<Duty> searchAllByStudentId(Integer)
}
class xyz.innky.graduationproject.web.service.impl.MenuServiceImpl {
+ List<MenuVo> getMenusByMenuIds(List<Integer>)
}
class xyz.innky.graduationproject.web.service.impl.SCourseTimeRelationServiceImpl {
}
class xyz.innky.graduationproject.web.service.impl.StudentServiceImpl {
~ DutyService dutyService
~ ClassInfoService classInfoService
+ Page<StudentVo> getAllStudents(Integer,Integer,String,Integer,String,String,String,String,String)
+ Long selectCountByClassId(Integer)
+ List<Student> getStudentsByClass(Integer)
+ List<Student> getAllStudentsByName(String)
}
class xyz.innky.graduationproject.web.service.impl.SpecificCourseServiceImpl {
}
class xyz.innky.graduationproject.web.service.impl.ExerciseSceneRelationServiceImpl {
}


com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.TeacherService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.SCourseTimeRelationService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.MaterialService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.SpecificCourseService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.ExerciseSceneRelationService
xyz.innky.graduationproject.web.service.impl.UserAccountService <|.. xyz.innky.graduationproject.web.service.impl.UserAccountServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.UserAccountServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.DeviceService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.StudentExerciseRelationService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.MenuService
xyz.innky.graduationproject.web.service.DeviceService <|.. xyz.innky.graduationproject.web.service.impl.DeviceServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.DeviceServiceImpl
xyz.innky.graduationproject.web.service.SceneService <|.. xyz.innky.graduationproject.web.service.impl.SceneServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.SceneServiceImpl
xyz.innky.graduationproject.web.service.ImageService <|.. xyz.innky.graduationproject.web.service.impl.ImageServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.ImageServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.DutyService
xyz.innky.graduationproject.web.service.DepartmentService <|.. xyz.innky.graduationproject.web.service.impl.DepartmentServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.DepartmentServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.DeviceSceneRelationService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.UserAccountService
org.springframework.security.core.userdetails.UserDetailsService <|-- xyz.innky.graduationproject.web.service.UserAccountService
xyz.innky.graduationproject.web.service.ExerciseService <|.. xyz.innky.graduationproject.web.service.impl.ExerciseServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.ExerciseServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.TeacherCourseClassRelationService
xyz.innky.graduationproject.web.service.RoleService <|.. xyz.innky.graduationproject.web.service.impl.RoleServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.RoleServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.StudentService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.StudentDeviceRelationService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.DepartmentService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.ClassInfoService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.CourseService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.CourseTimeService
xyz.innky.graduationproject.web.service.TeacherService <|.. xyz.innky.graduationproject.web.service.impl.TeacherServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.TeacherServiceImpl
xyz.innky.graduationproject.web.service.RoleMenuRelationService <|.. xyz.innky.graduationproject.web.service.impl.RoleMenuRelationServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.RoleMenuRelationServiceImpl
xyz.innky.graduationproject.web.service.StudentExerciseRelationService <|.. xyz.innky.graduationproject.web.service.impl.StudentExerciseRelationServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.StudentExerciseRelationServiceImpl
xyz.innky.graduationproject.web.service.ClassInfoService <|.. xyz.innky.graduationproject.web.service.impl.ClassInfoServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.ClassInfoServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.SceneService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.ImageService
xyz.innky.graduationproject.web.service.CourseTimeService <|.. xyz.innky.graduationproject.web.service.impl.CourseTimeServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.CourseTimeServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.RoleService
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.ExerciseService
xyz.innky.graduationproject.web.service.MaterialService <|.. xyz.innky.graduationproject.web.service.impl.MaterialServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.MaterialServiceImpl
xyz.innky.graduationproject.web.service.TeacherCourseClassRelationService <|.. xyz.innky.graduationproject.web.service.impl.TeacherCourseClassRelationServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.TeacherCourseClassRelationServiceImpl
xyz.innky.graduationproject.web.service.StudentDeviceRelationService <|.. xyz.innky.graduationproject.web.service.impl.StudentDeviceRelationServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.StudentDeviceRelationServiceImpl
xyz.innky.graduationproject.web.service.DeviceSceneRelationService <|.. xyz.innky.graduationproject.web.service.impl.DeviceSceneRelationServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.DeviceSceneRelationServiceImpl
com.baomidou.mybatisplus.extension.service.IService <|-- xyz.innky.graduationproject.web.service.RoleMenuRelationService
xyz.innky.graduationproject.web.service.CourseService <|.. xyz.innky.graduationproject.web.service.impl.CourseServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.CourseServiceImpl
xyz.innky.graduationproject.web.service.DutyService <|.. xyz.innky.graduationproject.web.service.impl.DutyServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.DutyServiceImpl
xyz.innky.graduationproject.web.service.MenuService <|.. xyz.innky.graduationproject.web.service.impl.MenuServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.MenuServiceImpl
xyz.innky.graduationproject.web.service.SCourseTimeRelationService <|.. xyz.innky.graduationproject.web.service.impl.SCourseTimeRelationServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.SCourseTimeRelationServiceImpl
xyz.innky.graduationproject.web.service.StudentService <|.. xyz.innky.graduationproject.web.service.impl.StudentServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.StudentServiceImpl
xyz.innky.graduationproject.web.service.SpecificCourseService <|.. xyz.innky.graduationproject.web.service.impl.SpecificCourseServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.SpecificCourseServiceImpl
xyz.innky.graduationproject.web.service.ExerciseSceneRelationService <|.. xyz.innky.graduationproject.web.service.impl.ExerciseSceneRelationServiceImpl
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl <|-- xyz.innky.graduationproject.web.service.impl.ExerciseSceneRelationServiceImpl
@enduml