@startuml
'skinparam linetype ortho
xyz.innky.graduationproject.web.vo.Result <.. xyz.innky.graduationproject.common.utils.ResultUtil
xyz.innky.graduationproject.web.service.ClassInfoService <.. xyz.innky.graduationproject.web.controller.admin.ClassController
xyz.innky.graduationproject.web.vo.Result <.. xyz.innky.graduationproject.web.controller.admin.ClassController
xyz.innky.graduationproject.web.vo.ClassStudentVo <.. xyz.innky.graduationproject.web.service.ClassInfoService
xyz.innky.graduationproject.common.utils.ResultUtil <.. xyz.innky.graduationproject.web.controller.admin.ClassController
xyz.innky.graduationproject.web.pojo.ClassInfo <.. xyz.innky.graduationproject.web.controller.admin.ClassController
xyz.innky.graduationproject.web.vo.ClassInfoVo <.. xyz.innky.graduationproject.web.service.ClassInfoService
xyz.innky.graduationproject.web.pojo.ClassInfo <|-- xyz.innky.graduationproject.web.vo.ClassInfoVo
xyz.innky.graduationproject.web.service.ClassInfoService <--* xyz.innky.graduationproject.web.controller.admin.ClassController
xyz.innky.graduationproject.web.pojo.ClassInfo <.. xyz.innky.graduationproject.web.service.ClassInfoService
xyz.innky.graduationproject.web.pojo.ClassStudentRelation <|-- xyz.innky.graduationproject.web.vo.ClassStudentVo
@enduml