server:
  port: 8081
  address: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_design
    username: root
    password: '000508'
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    xyz.innky.graduationproject: debug

openstack:
  baseurl: '192.168.50.53'
static:
  path: "/Users/xingyijin/IdeaProjects/graduationProject/src/main/resources/static/"

#  spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#  spring.jackson.time-zone=GMT+8

