server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_design
    username: root
    password: '000508'
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    xyz.innky.graduationproject: debug
