@startuml
class xyz.innky.graduationproject.web.controller.admin.AccountController {
- UserAccountService userAccountService
+ Result addAccount(UserAccount)
+ Result updateAccount(UserAccount)
+ Result deleteAccount(Long)
+ Result getStudentAccounts(Integer,Integer,String,Integer,String)
+ Result getTeacherAccounts(Integer,Integer,String,Integer,String)
+ Result getAccounts(Integer,Integer,String)
}
class xyz.innky.graduationproject.web.controller.admin.StudentController {
- StudentService studentService
+ Result addStudent(Student)
+ Result updateStudent(Student)
+ Result deleteStudent(Integer)
+ Result getAllStudent(Integer,Integer,String,Integer,String,String,String,String,String)
}
class xyz.innky.graduationproject.web.controller.admin.TeacherController {
~ TeacherService teacherService
~ Result addTeacher(Teacher)
~ Result deleteTeacher(Integer)
~ Result updateTeacher(Teacher)
~ Result getTeacher(Integer,Integer,String,Integer,String,Integer)
}
class xyz.innky.graduationproject.web.controller.admin.ClassController {
~ ClassInfoService classInfoService
~ Result getAllClass(Integer,Integer,String,String,String,String)
~ Result getClassById(Integer)
~ Result deleteClass(String)
~ Result updateClass(String,ClassInfo)
~ Result addClass(ClassInfo)
}
class xyz.innky.graduationproject.web.controller.admin.DepartmentController {
~ DepartmentService departmentService
~ Result addDepartment(Department)
~ Result deleteDepartment(Integer)
~ Result updateDepartment(Department)
~ Result getAllDepartment(Integer,Integer,Integer,String)
}
@enduml